# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00148 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.148"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.148/agentuity_Darwin_x86_64.tar.gz"
      sha256 "188af6caa21f2e5f787aafc8d36213394b4d5467055ca32a5663f5848abd3d13"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.148/agentuity_Darwin_arm64.tar.gz"
      sha256 "4f3c59d7972d7af71e7d553f5d130fffb9c433b670e755f9c4ab3c53541ad96e"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.148/agentuity_Linux_x86_64.tar.gz"
      sha256 "d394e96a9f0386c20d03ddd3dd8c064220246220e8798994f37c2ee11fb93c3e"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.148/agentuity_Linux_arm64.tar.gz"
      sha256 "875b2519c5d6de5e60a4915c61e6ee7a80a27ca531c78b99b927e930708d3347"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
