# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00164 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.164"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.164/agentuity_Darwin_x86_64.tar.gz"
      sha256 "d49761ee9d753f0db24967970e01b1ef0d8cda464df2971b7033c6b8e36a9bfe"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.164/agentuity_Darwin_arm64.tar.gz"
      sha256 "a75649602c47696971db83735ddefff799285db51288f392d50ba1c550eba50b"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.164/agentuity_Linux_x86_64.tar.gz"
      sha256 "54fdaf76db0817fdd2527f4ffe387c9b372d9e70c6a34918ad67efaf47e8a599"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.164/agentuity_Linux_arm64.tar.gz"
      sha256 "de884b888c917d1a374c3057da94c8369b37c5a34ad095813c5b6dc32da3c78b"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
