# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0059 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.59"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.59/agentuity_Darwin_x86_64.tar.gz"
      sha256 "eab83b9e2b7e09cc1154ca2e57fedda249c7bc02a4bba4ab1147cbd4938d3a3c"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.59/agentuity_Darwin_arm64.tar.gz"
      sha256 "02c7fe100de5595df5dace22226696d1d00fd53047336b17457ed9150068d5c0"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.59/agentuity_Linux_x86_64.tar.gz"
        sha256 "ec5ce26d3f117c7d1be8fa07c055bfa4a8253e5c855b8ee8d00bef90c499603a"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.59/agentuity_Linux_arm64.tar.gz"
        sha256 "dddad40e88e51a0e295ad8b52f7e1d933e5309daae334dc687c9181e0ff18447"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
