# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00174 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.174"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.174/agentuity_Darwin_x86_64.tar.gz"
      sha256 "3c45590be95446a5d81ab11d240317629f35686bd55eef23da3a5e2da0e66b62"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.174/agentuity_Darwin_arm64.tar.gz"
      sha256 "4a8acd9e9246c81dd95ca2ebed90a01b1fdce4e7a2ba6d8eab9fcf3e3a367057"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.174/agentuity_Linux_x86_64.tar.gz"
      sha256 "b694ae93869f97486b915add345c58557758ff9553ec35441465cd953dda3de6"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.174/agentuity_Linux_arm64.tar.gz"
      sha256 "c731359b7797adb311aae608cc4d1e264e93e849fd555279df24e20de4e1e761"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
