# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0022 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.22"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.22/agentuity_Darwin_x86_64.tar.gz"
      sha256 "3fafd9d5f5bd543c705443d584be1dd6380d014a245ff5795ef01fea0e399387"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.22/agentuity_Darwin_arm64.tar.gz"
      sha256 "8e31fc52426bdc28367e447917726eca48b841b1f7670ba8220666d7e7794391"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.22/agentuity_Linux_x86_64.tar.gz"
        sha256 "bc8da2830982d77da2592a6f70e13f0753dbca671b6ee243fe0fde6f6913c7d1"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.22/agentuity_Linux_arm64.tar.gz"
        sha256 "fb3b1593ec80f09e294bb3793dd6a70e87401594161a558bc5e845cfd2e06397"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
