# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0023 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.23/agentuity_Darwin_x86_64.tar.gz"
      sha256 "4e075711dd0a5a88a986ff31ba881594d1df7011e37bc14d67b6958694bbecf6"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.23/agentuity_Darwin_arm64.tar.gz"
      sha256 "23f77651a5ded914e7d3f619960e96a50447824dbdb0dcb537974fcc948ef176"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.23/agentuity_Linux_x86_64.tar.gz"
        sha256 "0bf614136829144e5157c4367b32a293f03badf271e759fcb6a68c7df9c802c0"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.23/agentuity_Linux_arm64.tar.gz"
        sha256 "c7ba022e1f7f1beb33bdccb47dfab7d0c0978dca816557c0ebb05a36fa283b96"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
