# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00170 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.170"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.170/agentuity_Darwin_x86_64.tar.gz"
      sha256 "36f4a475fdeff204771f9acff83e9e617902c91d71b3a09db4a90b25b24c2c5a"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.170/agentuity_Darwin_arm64.tar.gz"
      sha256 "833cb2a0e43c4470a61a9260e84771564bd15220501b420d732b39e2efd4338d"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.170/agentuity_Linux_x86_64.tar.gz"
      sha256 "abd91b97519c57d0955b5ac78c712fa10040f0298e994b385e8809fbb7bdc64a"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.170/agentuity_Linux_arm64.tar.gz"
      sha256 "ed175299fb45a386fb2dff2327cc1ad278f12b642531a967297bbe0c335a4593"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
