# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00107 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.107"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.107/agentuity_Darwin_x86_64.tar.gz"
      sha256 "6e952490897730c3f4e8474f83f7b9b1a438cf85e7cb6da70162c2df1fd11416"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.107/agentuity_Darwin_arm64.tar.gz"
      sha256 "86990a35aad36f7a06ac3c038e9681d31c165f053060c8b1026fa1218384fa7b"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.107/agentuity_Linux_x86_64.tar.gz"
        sha256 "e915a326b9ccbdad17b49488cb354d5059fe3dd4126d6e6ae4348a997e875a77"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.107/agentuity_Linux_arm64.tar.gz"
        sha256 "6f9d5d4942e9a853e56d823bf5cf8b011351efd387a94968d852e5e63860978e"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
