# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0041 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.41"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.41/agentuity_Darwin_x86_64.tar.gz"
      sha256 "74fd9caaf918a71ca1be2711a33eb62fc33bd7a517932c717a6771ed6fe9e01a"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.41/agentuity_Darwin_arm64.tar.gz"
      sha256 "28d1d04f7d7914fb45776dc11a9fbf717fbd38f35e4f4cfa142243b37a52247d"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.41/agentuity_Linux_x86_64.tar.gz"
        sha256 "673152e54287218841f4ebe00d06b90852f19f41bc10fd17f927b08312893b9f"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.41/agentuity_Linux_arm64.tar.gz"
        sha256 "ac197b0cbe513f4e6ec6b55779eef9d05ec0910f0fa398f12d201440d5052da8"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
