# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00156 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.156"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.156/agentuity_Darwin_x86_64.tar.gz"
      sha256 "cc64554ffd02f7ce419a20fefb0e922d5f8bd00ca64665b54ec5be3170703243"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.156/agentuity_Darwin_arm64.tar.gz"
      sha256 "2dcedb1e59f39d358ae287c97140ea9de2130b5d4a833e0c9b1f1322a0bbc900"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.156/agentuity_Linux_x86_64.tar.gz"
      sha256 "b467eacd013b2def042e7076d3e48fcb52ff9129820a93f5c77ef8ec334a3950"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.156/agentuity_Linux_arm64.tar.gz"
      sha256 "4e8955e48a39a8ad3c796491d5f4509e59fc6c0c72dfd1f21a740f9a0737ece1"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
