# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0015 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.15/agentuity_Darwin_x86_64.tar.gz"
      sha256 "6aaa68d17fa29ceb474d42289de8c5a25f8d2a236b18adbc20a34b92124c38a0"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.15/agentuity_Darwin_arm64.tar.gz"
      sha256 "60c74a6792cb40ca010917c874f741230b7acecbfff9b64667f2be20d377248f"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.15/agentuity_Linux_x86_64.tar.gz"
        sha256 "c313a36874524b761292bee6751e6b94a5928333b19c3ed4b04563fcee103c9a"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.15/agentuity_Linux_arm64.tar.gz"
        sha256 "fcb995865e2fe240b68c450e2a2eb9f6243bd32552e427ef6d966bc684cd5cce"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
