# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00129 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.129"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.129/agentuity_Darwin_x86_64.tar.gz"
      sha256 "42be41628d271dc1563d0987dd46022ff476a40bcac7b4ac83f60c7a9bd42847"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.129/agentuity_Darwin_arm64.tar.gz"
      sha256 "07422c1e4b2491186e98a9f417e6fa93036d2aca764e20d9f0694d1af4312705"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.129/agentuity_Linux_x86_64.tar.gz"
      sha256 "4b10f040c008640325839e62de0fdb079feab89c3be1dbd81c9948b968d1738f"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.129/agentuity_Linux_arm64.tar.gz"
      sha256 "6f288f2306a7deb90dc6d630c424c2e7902e6df2f8f7e320a543c56336c61c72"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
