# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00153 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.153"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.153/agentuity_Darwin_x86_64.tar.gz"
      sha256 "e81564dab736c392048c866953c1111eba30acbf3153015b7985424477c4ab11"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.153/agentuity_Darwin_arm64.tar.gz"
      sha256 "0b1ddf52387cf1df3853496d09544ab5c34e0c4fad85472cf0323974aac85728"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.153/agentuity_Linux_x86_64.tar.gz"
      sha256 "2ddf16729254103b8f4081185a445761942b323229dd1f5bbd042bd30b4a5d0f"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.153/agentuity_Linux_arm64.tar.gz"
      sha256 "f3331762a27b4683efee376d3346d383468a01548a7cf406d4751e57effc269b"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
