# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0085 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.85"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.85/agentuity_Darwin_x86_64.tar.gz"
      sha256 "0d28100749fb7019a27c283c544ab28907175e0a42b25b81c368d9dfc8304b82"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.85/agentuity_Darwin_arm64.tar.gz"
      sha256 "40efb0c515d8d17a89c4f93b497925387cfc4d3f2d68a3c0c085d2a96207da98"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.85/agentuity_Linux_x86_64.tar.gz"
        sha256 "37fed02239df08125e2054c2775e86fa3e5fbbc6a5d13ab2834ba800b5564423"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.85/agentuity_Linux_arm64.tar.gz"
        sha256 "87004d3ffc66e996c0e4a299b71a95fb6fbcc8bc466403fb699f68340f6076b6"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
