# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0081 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.81"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.81/agentuity_Darwin_x86_64.tar.gz"
      sha256 "cadc2cf48bf070b7b935a48b4df407771672caf46f654e87ceb89fa445c945c2"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.81/agentuity_Darwin_arm64.tar.gz"
      sha256 "17c902b536472cc535cfd309af648c055c99bc7c9cd48e4d0ee55fbdfde4313a"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.81/agentuity_Linux_x86_64.tar.gz"
        sha256 "519e11b8cf26e5b3a3180044baa544f00dc28d7d7b8c88ab02c01497be8dbe73"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.81/agentuity_Linux_arm64.tar.gz"
        sha256 "885ba1e502841c33672eb2b597254306bd1a87325fdb24c499386496b4d96ccd"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
