# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0076 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.76"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.76/agentuity_Darwin_x86_64.tar.gz"
      sha256 "99b829f8f0415a42d79028a927f20f69929ac2fec3f6b4a6c887a5d6001fa3ef"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.76/agentuity_Darwin_arm64.tar.gz"
      sha256 "4f18a1134c2a2be8cc58c386fee35ca8980053c854931a570f1db20110b6e540"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.76/agentuity_Linux_x86_64.tar.gz"
        sha256 "16924d197cf4843bccf3d63b8237610ac835877f74eee09335195d576c1b5342"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.76/agentuity_Linux_arm64.tar.gz"
        sha256 "f3fac3dac655c123f331b643636a264169236f276bc6536b1d4bca3aef6f5b8c"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
