# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0016 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.16/agentuity_Darwin_x86_64.tar.gz"
      sha256 "5c99ea769791b9195d510a054327e43c203c68835d79665bb883877d1518c20c"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.16/agentuity_Darwin_arm64.tar.gz"
      sha256 "984daf1db5fb23d4f616f0ab6e73dd0138e49761111abe4d21d951487ffd318c"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.16/agentuity_Linux_x86_64.tar.gz"
        sha256 "34bc71c2af12c49961a74fce4a742f20e5a2187703700cd2fe310c047bc1ea3b"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.16/agentuity_Linux_arm64.tar.gz"
        sha256 "d193b9e507c8ff3a03780edcb1ff007e2a8661afef611469fb262ab25fd6cbba"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
