# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00171 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.171"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.171/agentuity_Darwin_x86_64.tar.gz"
      sha256 "833f943ea77aea1ebad24818ea759caa3af9a1c6cbdb166604a4e70039b69f27"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.171/agentuity_Darwin_arm64.tar.gz"
      sha256 "4484e90f9c93ee6e8a1c6e7c2ba82dfd5ebc1cb6d0a57bf3ae666fe0b9ecee66"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.171/agentuity_Linux_x86_64.tar.gz"
      sha256 "fa72e1d94f9d29746b025732511a031d79172af10176e7bd83fedb601489ebf3"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.171/agentuity_Linux_arm64.tar.gz"
      sha256 "ad764727bc53d0c3678c2b83724fde6e93828c1b8254517b4578debe42c219ef"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
