# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00173 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.173"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.173/agentuity_Darwin_x86_64.tar.gz"
      sha256 "86adfdca9d258a50e7cccff7e8c983a0d02af5ec78277e43095476c2795b8dca"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.173/agentuity_Darwin_arm64.tar.gz"
      sha256 "17154e7dfa48c401752c44ff7037a79905c9dd8f93f6a74451dd0697a1112ed5"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.173/agentuity_Linux_x86_64.tar.gz"
      sha256 "9462d535be74f3eaa0151af564bacfd1cc56376369a955f02906752029ae4374"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.173/agentuity_Linux_arm64.tar.gz"
      sha256 "6731b05bfa13015dce9b46f77f2eb50784de7f136dccab305758af1e7be9040d"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
