# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00146 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.146"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.146/agentuity_Darwin_x86_64.tar.gz"
      sha256 "cec66efabae13668850ec665268fb591ed62b01e95a0a975b3f61cb81f6509e5"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.146/agentuity_Darwin_arm64.tar.gz"
      sha256 "8262d6716e88a1dcf68ddfb0986fe2680e3b90d6ea5870c6f69d7019a06adf24"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.146/agentuity_Linux_x86_64.tar.gz"
      sha256 "6dd91c2db1e952755730f9b7061cbb99711aa18791b19282b38a4d1fa7799716"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.146/agentuity_Linux_arm64.tar.gz"
      sha256 "7b6103c4a3155c5e6d01986053b43d0edf1c85191ed304a7097b3a7cf7165720"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
