# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00142 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.142"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.142/agentuity_Darwin_x86_64.tar.gz"
      sha256 "b41f162ea6935453f2833898b3df18706ffbae7b20ee19a7a146ec7142a39c96"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.142/agentuity_Darwin_arm64.tar.gz"
      sha256 "6248a65cd4f346b09d3e2ed24b7dc99cab396b932eefd6d210f56eb43c8ec880"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.142/agentuity_Linux_x86_64.tar.gz"
      sha256 "410f76662e7d38ef0c13de3084c6f77cd587e441f73c069613e555a987b0c62c"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.142/agentuity_Linux_arm64.tar.gz"
      sha256 "4359d2e19ec2eeb46790fd655cb3365cf77ec1e6fdbc3e3e5d72693cfdc25682"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
