# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0061 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.61"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.61/agentuity_Darwin_x86_64.tar.gz"
      sha256 "d50ce960ce69bfb95ecfd1c6282af9be48dbbee1466b06b830e03969c2fb0fe2"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.61/agentuity_Darwin_arm64.tar.gz"
      sha256 "71964a9ca97a3ac8036a118bc6a15dfe341f42c27053e6530316a60b113962d8"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.61/agentuity_Linux_x86_64.tar.gz"
        sha256 "8e43133504d8ef55401accf14b78466681c2ebdf4f20504bc61d7232d6926bf0"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.61/agentuity_Linux_arm64.tar.gz"
        sha256 "30bbbd3b3e34a026079478b304bc87274f1f5f6aee0b1c9a25fa08e1f22652bf"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
