# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0060 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.60"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.60/agentuity_Darwin_x86_64.tar.gz"
      sha256 "ba3e48200b25d01b32ddb2b93371cf6c18255b239fb4c19a9ba6cbb489a7ee1a"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.60/agentuity_Darwin_arm64.tar.gz"
      sha256 "4c8a5222e81a57c4f4d5517558e613e1b98df39b747f8468c6e69edaee99a2a3"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.60/agentuity_Linux_x86_64.tar.gz"
        sha256 "2b3088f4d03115bb89f8e528f7635c89b96f1a848ae6da9abd793b71cc96fcfa"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.60/agentuity_Linux_arm64.tar.gz"
        sha256 "97b72e968dca691e669681a2e318381be1ca16ff200a3b455b716cbf09983694"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
