# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00131 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.131"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.131/agentuity_Darwin_x86_64.tar.gz"
      sha256 "61f95c16fb51ecb7d704afcd8019c04a9a54ca28b9f7e8c76e1fa6cfa2cd4b80"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.131/agentuity_Darwin_arm64.tar.gz"
      sha256 "c0629d922d811c0c6d379264bfe5db259efea7d59bfec9a7fe6d75f65efa3027"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.131/agentuity_Linux_x86_64.tar.gz"
      sha256 "2f201cec7e2b0a6a3615925f5795d75809f3061815b275843f53b447863e1a75"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.131/agentuity_Linux_arm64.tar.gz"
      sha256 "8583970b528cb2cdbc479a400fa52d43983235430ce08c830f5d6573dbd1b5dd"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
