# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00126 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.126"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.126/agentuity_Darwin_x86_64.tar.gz"
      sha256 "4fe47af34666e7c51169d43de0d403fe62152bbdf1487772fb6c599e194bf058"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.126/agentuity_Darwin_arm64.tar.gz"
      sha256 "cb8b5a824f8a658023c440aacbd01751ed97c40cdc0dd519ad8d0556675fc8d3"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.126/agentuity_Linux_x86_64.tar.gz"
      sha256 "216b178fdc62c7177069c078d2d99b32dc9c6b2127d9cf6b2d195091b088989c"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.126/agentuity_Linux_arm64.tar.gz"
      sha256 "af3271b9745d9e3a61b7503c898ebc142f0a3e3117332d27c1bb9cb9c1a4b6ea"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
