# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0030 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.30"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.30/agentuity_Darwin_x86_64.tar.gz"
      sha256 "f975caf5b22d5e1de651fa7f4ea4f7ea75362a21d99afaccff7075305f97f215"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.30/agentuity_Darwin_arm64.tar.gz"
      sha256 "9d4b8446bea540bb9d312302df8a9e9e53b02c61aeee1edfb996f5fe9889f2a9"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.30/agentuity_Linux_x86_64.tar.gz"
        sha256 "cada86aaee20f04bf9307dd4c549029135b4a472edcc22cd73703c57305c5a05"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.30/agentuity_Linux_arm64.tar.gz"
        sha256 "f61327fda19be86855e52ea06309f7ade642c1991d3f033be9ca6d17dfc9a324"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
