# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0043 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.43"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.43/agentuity_Darwin_x86_64.tar.gz"
      sha256 "92a4e67786cbf6ad5093378b08d41276617d4ee00ad3a6fc5b156e888eb73a44"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.43/agentuity_Darwin_arm64.tar.gz"
      sha256 "282545de68b6c6898c2cc758b56301b426303d904093cbd679d38a634d5aa2ad"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.43/agentuity_Linux_x86_64.tar.gz"
        sha256 "7cf95cca9cd59cf0ccd058651c2fe14465dc58641b33b9bed74a144d0e47051c"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.43/agentuity_Linux_arm64.tar.gz"
        sha256 "6db8e83225d092ef380047ad4f371b29ce03040b3a82921af5e35c065df7645f"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
