# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00138 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.138"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.138/agentuity_Darwin_x86_64.tar.gz"
      sha256 "20aa8c483e4e5bcaaffbc2b3aff2c86849615c8405b9cff6e86acafde8b53196"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.138/agentuity_Darwin_arm64.tar.gz"
      sha256 "43b18afa68743b29aa0dd938886ec69649441b3975fdab35806c6ab33c3299eb"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.138/agentuity_Linux_x86_64.tar.gz"
      sha256 "f83b3fad6cb169e242ef8e473e460fe694d2e8bc9164fd4e10ebdda4fa5dda6f"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.138/agentuity_Linux_arm64.tar.gz"
      sha256 "ba4057e69bb444bdfb9abb068e63b72198fc754b19354ced7d6727d2f6dc653f"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
