# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00111 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.111"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.111/agentuity_Darwin_x86_64.tar.gz"
      sha256 "720e6e13fecb5630d355a134ac0a9630fd32a6df36f9af4eeecc28ac3f4afc56"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.111/agentuity_Darwin_arm64.tar.gz"
      sha256 "2950a6745f484cbc4a817ef2237fd9fb781c70513b39cb2da22644f48b64931b"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.111/agentuity_Linux_x86_64.tar.gz"
        sha256 "6d7287b2aca684637975cecdb61c4a5df94e74851829f13e04d25b2df2d4c17f"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.111/agentuity_Linux_arm64.tar.gz"
        sha256 "3c20d6892bdcfc6ba80cf0fcf9ceb703cae2ad1bb45c332d0335b6df83796b3a"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
