# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0088 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.88"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.88/agentuity_Darwin_x86_64.tar.gz"
      sha256 "a97a085addce046b4b5e076b8f7ce86cf2a312b57b2050af4b70948dcbcd90c9"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.88/agentuity_Darwin_arm64.tar.gz"
      sha256 "e6ecdeb0e9146be9faf73843d72837f209f3aec3e034b9860c352ec9f42d9e3e"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.88/agentuity_Linux_x86_64.tar.gz"
        sha256 "0410e5c76fe69d3697bfbf06b58b456c05606563d6d186e88ffb09ffe810d6e1"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.88/agentuity_Linux_arm64.tar.gz"
        sha256 "9020ede2ca594e5bb6caca6467c670552ee31e313a2c935887ef395c5f341f1f"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
