# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00109 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.109"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.109/agentuity_Darwin_x86_64.tar.gz"
      sha256 "914098281299e8a9944c4b04d81b7d89164a4f48d83d180abea2ab49e17a2081"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.109/agentuity_Darwin_arm64.tar.gz"
      sha256 "2b146f71e12bbf67c4626451a040d3883dfd7e60c05c0558e07bdeab43c3add8"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.109/agentuity_Linux_x86_64.tar.gz"
        sha256 "ad78c3c1037d0aef64921fed42e3c175ff7e86b1c216ffd29b7828eead27bc2f"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.109/agentuity_Linux_arm64.tar.gz"
        sha256 "1ccb305b064e870025df29bc2209afc54aca050f6bc70255d972f87124ae30f0"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
