# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0024 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.24"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.24/agentuity_Darwin_x86_64.tar.gz"
      sha256 "e88dc9990ac93f0f10e6213bcfabccda8e8339b91fbea4e57f2e79db00551ee4"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.24/agentuity_Darwin_arm64.tar.gz"
      sha256 "8dd88d7efda5c9d5b19a94fd0a69b9036c5eb27ae245f2c554350ae52faed93d"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.24/agentuity_Linux_x86_64.tar.gz"
        sha256 "ca52455a48b71ad23b769fdd886a48ab0ffed22610c1ccb75d73b05673e89159"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.24/agentuity_Linux_arm64.tar.gz"
        sha256 "5e7f2dcc06a896122db532c091b78f39310fbd7be194ed3f452b000a82020773"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
