# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00112 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.112"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.112/agentuity_Darwin_x86_64.tar.gz"
      sha256 "b1d9a3ae7155388016ae8721d39f5bd107ebaefdf236f436955416e490532c05"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.112/agentuity_Darwin_arm64.tar.gz"
      sha256 "b79040cb02c25a837b7b94238887b847b22cc6dc89697708caedb41b2392a9e3"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.112/agentuity_Linux_x86_64.tar.gz"
        sha256 "70fd1f967131fbfad97a4b388b523c7b01c536eb35079703e24a6599d25ce0e0"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.112/agentuity_Linux_arm64.tar.gz"
        sha256 "b7a247c96c98f0e297bac057b4c233f9b33f6f30168e68e0d73798cd0159cffb"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
