# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentuity < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.40"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.40/agentuity_Darwin_x86_64.tar.gz"
      sha256 "e9a926c23fad331c7a51c03e02542583ceecd5fedd7697f4a3739f1b6427ce02"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.40/agentuity_Darwin_arm64.tar.gz"
      sha256 "494c6c6fa3a6adadbe7fab621a662360bb07a6adca83f54f26f36981b4071d12"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.40/agentuity_Linux_x86_64.tar.gz"
        sha256 "12cfa3d219e892dbb7dca7f1726f49034af546cb3b475f772e839afc13eab32a"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.40/agentuity_Linux_arm64.tar.gz"
        sha256 "a4587e8f2b68db455d0392fbf18796b8c29b6a44ea576e8822a19e2569257b05"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
