# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00120 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.120"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.120/agentuity_Darwin_x86_64.tar.gz"
      sha256 "e4a155e4d20a893a8db5f929c3a2951dfe664a5c040711d730b4d30da1ffbbd2"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.120/agentuity_Darwin_arm64.tar.gz"
      sha256 "ef96a6c0f14fb3c840aa30383d8dca3486a97d5fb73bc84bda59d6aa906ad816"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.120/agentuity_Linux_x86_64.tar.gz"
        sha256 "09fa78127cb9ec0c122424c1b0a84fa312d9140938e3cf916d94b7d00c8e172d"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.120/agentuity_Linux_arm64.tar.gz"
        sha256 "ac530ad986db41eac67f1d37a77924558062764935606db3d5eaaa7edf377e2d"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
