# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00113 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.113"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.113/agentuity_Darwin_x86_64.tar.gz"
      sha256 "1fe33f98875daefd2fbdcf4d331ee7e2e04c733f9406d1ce2348101aef89919d"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.113/agentuity_Darwin_arm64.tar.gz"
      sha256 "8e53f5795f5f2f631a2d2f0e6b53bbbc6eecb42f7dcd0bc91c8616d64aa027a8"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.113/agentuity_Linux_x86_64.tar.gz"
        sha256 "14e4d212199dec3e57c95cf939d1ef598038f848b71ae8fb523fe5b059f54925"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.113/agentuity_Linux_arm64.tar.gz"
        sha256 "cf58cabd6d07c6e52ac4f8ae9a620beed9efad978ed29556ecbfe067e59f1109"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
