# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0091 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.91"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.91/agentuity_Darwin_x86_64.tar.gz"
      sha256 "ffa32710576c16319703a370bf3d16cb9d2bbc4326a3f33de041913d322341e9"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.91/agentuity_Darwin_arm64.tar.gz"
      sha256 "f12c4508b5dd9955ac3e4011edadc4338c0ff2133aae23c3870cf4bf37042787"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.91/agentuity_Linux_x86_64.tar.gz"
        sha256 "77c956ffd310ebc5d758e0d05fe379943801b967cbc0c86e61b1ef1eb7373c86"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.91/agentuity_Linux_arm64.tar.gz"
        sha256 "2515a6c019edec466360b7d90983a29571348835d1da7ff1f59c54f0c3a46c58"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
