# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentuity < Formula
  desc "Agentuity CLI"
  homepage "https://agentuity.com"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.4/agentuity_Darwin_x86_64.tar.gz"
      sha256 "bcbabfabfb9cca27682da71c3162d4887bfd07c72b0eb5bc9d5e2aa2fea5e6fc"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.4/agentuity_Darwin_arm64.tar.gz"
      sha256 "22fb40b0dece71c13950c6d7791d64c4c453b3f2ab222e8b648a4d1727bcdef5"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.4/agentuity_Linux_x86_64.tar.gz"
        sha256 "c583d6f6f3ce6a4786f7d9b84a1f4cf993ae444f93ad413f9491e64eded5e8d0"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.4/agentuity_Linux_arm64.tar.gz"
        sha256 "bbdd6ae7901280c9aed15e80f9f813a7bc8a7cefab114b59d40d5ab3a55c881a"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
