# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0020 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.20"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.20/agentuity_Darwin_x86_64.tar.gz"
      sha256 "0d8a9bd5823bddf1e9fbe24dff09f8999bc20e7350a306ac9201a5527d0f5aa8"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.20/agentuity_Darwin_arm64.tar.gz"
      sha256 "3bdfe97fcdea23b771cb8cfd3d589c90d85d8165a8b7873cbd5360f9841267c5"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.20/agentuity_Linux_x86_64.tar.gz"
        sha256 "bfd23af46519c829ed35e11787f441a46b955aa2512518d91944507bcac1f01d"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.20/agentuity_Linux_arm64.tar.gz"
        sha256 "ff3c013dd1bc54d87e2cda413304ce0825a7720ab42de508f10e2445e2c9033d"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
