# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00121 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.121"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.121/agentuity_Darwin_x86_64.tar.gz"
      sha256 "e68b7fcbf1f6204a4a2fbf721a9e3faa99e1dae78ab6a8909de691e9ebdda8d1"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.121/agentuity_Darwin_arm64.tar.gz"
      sha256 "ddfe58524615271fa6ddf925dc0845d1596ae226375c2366588d8511df14b8c8"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.121/agentuity_Linux_x86_64.tar.gz"
      sha256 "eee32d9952a3f643447c38475fe4965ea9f5c35a90f5e232f9b6917b18246b80"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.121/agentuity_Linux_arm64.tar.gz"
      sha256 "f8cde2088f481d99ed3684a346474ff61f1f8ad8e4b023ce61113dadb9f48e0c"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
