# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00143 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.143"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.143/agentuity_Darwin_x86_64.tar.gz"
      sha256 "fd2fd493322b730ce93d93a3c6e3baad04ec5a48870208513be942d8dc55d1a2"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.143/agentuity_Darwin_arm64.tar.gz"
      sha256 "d7d35f961499f10f24f58b59432292a7f40522f4567fd7d4c5461402b12f9410"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.143/agentuity_Linux_x86_64.tar.gz"
      sha256 "2769e9308662f38e1e016b9ae43dbbd9ed112590cbd85830c7de533feb213745"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.143/agentuity_Linux_arm64.tar.gz"
      sha256 "873b8ce33a22429b1dac33098f2b2cf19517fa05d849e0e60d314d6b4dfb7784"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
