# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT0012 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.12/agentuity_Darwin_x86_64.tar.gz"
      sha256 "b1d51547d6e6ab1ce49931248ad42544de31a748248127d842b3291a788b8253"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.12/agentuity_Darwin_arm64.tar.gz"
      sha256 "d23e95ab65f3a8d03d073c170e97c00aec41102966668dcd977fa8841459a4a8"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.12/agentuity_Linux_x86_64.tar.gz"
        sha256 "46e1940160c55f356eaa586b566fa457ae79b104f19fe42fdcb04f930b131e43"

        def install
          bin.install "agentuity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/agentuity/cli/releases/download/v0.0.12/agentuity_Linux_arm64.tar.gz"
        sha256 "adf91f024ae867c469c923d3d09510d811b6ea22a5329bf415da9f1b17ea33d0"

        def install
          bin.install "agentuity"
        end
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
