# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00157 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.157"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.157/agentuity_Darwin_x86_64.tar.gz"
      sha256 "428c5e1d25da43cd20832341e54898958d0b7f7bf8b38fe202b480e1adaad42b"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.157/agentuity_Darwin_arm64.tar.gz"
      sha256 "8e9471767b1b234f4aed17b3bf566e7052fa9ae475ef3eabfce999976ced1fd4"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.157/agentuity_Linux_x86_64.tar.gz"
      sha256 "608baf9701e9736e391caa58974d5664e1eed1b64350e9c0eb627cdd1a1573fd"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.157/agentuity_Linux_arm64.tar.gz"
      sha256 "8b7eee22b5fe72967b4d91f3e718ce9b85d2de9723c7d970a97751f21dfada76"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
