# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentuityAT00119 < Formula
  desc "Tooling for the Agentuity Agent Cloud Platform"
  homepage "https://agentuity.com"
  version "0.0.119"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentuity/cli/releases/download/v0.0.119/agentuity_Darwin_x86_64.tar.gz"
      sha256 "cbbc6d6f2a6ef37d1803239759e6ff2554c27d648d8510038946f616af0e0bae"

      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentuity/cli/releases/download/v0.0.119/agentuity_Darwin_arm64.tar.gz"
      sha256 "f223e810f66946110b4ac52fa416a6fea19f05840e71c6d5ca7a450bf8c35b3f"

      def install
        bin.install "agentuity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.119/agentuity_Linux_x86_64.tar.gz"
      sha256 "f8ae7e4edcacd48fd285b08c23c79b8677410fdb4f64d4e98eb5d6af6fc5b53e"
      def install
        bin.install "agentuity"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentuity/cli/releases/download/v0.0.119/agentuity_Linux_arm64.tar.gz"
      sha256 "3efb4504d1c2be32fd1f44562dee9cca41febdd5b51c45b27a4baf1535b1e8ad"
      def install
        bin.install "agentuity"
      end
    end
  end

  conflicts_with "the_silver_searcher"
end
